version: '3.8'

services:
  webscraper:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./output:/app/output
      - ./temp:/app/temp
      - ./logs:/app/logs
      - ./data:/app/data
      - ./drivers:/app/drivers
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_APP=server.py
      - FLASK_ENV=production
    restart: unless-stopped 